[workspace]
resolver = "3"
members = ["crates/mai-protocol", "crates/mai-core", "crates/mai-probe"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
mai-protocol = { path = "crates/mai-protocol" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
toml = "1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
