[package]
name = "mai-core"
version.workspace = true
edition.workspace = true

[dependencies]
keyring = "4"
mai-protocol = { workspace = true }
russh = { version = "0.63", default-features = false, features = ["flate2", "ring", "rsa"] }
russh-sftp = "3"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11"
ssh2-config = "0.8"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
ssh-key = { version = "=0.7.0-rc.11", features = ["getrandom", "ed25519", "encryption"] }
tempfile = "3"

[lints]
workspace = true
